mptindicators/scorecard/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from .models import Country, Section
from .views import (CountryList, CountryDetail, SectionList,
    IndicatorList, SectionDetail, SubsectionDetail, IndicatorDetail,
    CountryData, IndexView)


class MPTTemplateView(TemplateView):
    def get_context_data(self, **kwargs):
        context = super(MPTTemplateView, self).get_context_data(**kwargs)
        context['countries'] = Country.objects.all()
        context['sections'] = Section.objects.all()
        return context


urlpatterns = [
    url(r'^countries/$',
        CountryList.as_view(), name='scorecard_countries'),
    url(r'^countries/(?P<code>[\w-]+)/$',
        CountryDetail.as_view(), name='scorecard_country'),
    url(r'^countries/(?P<code>[\w-]+)/data/$',
        CountryData.as_view(), name='scorecard_country_data'),
    url(r'^indicators/$',
        IndicatorList.as_view(), name='scorecard_indicators'),
    url(r'^sections/$',
        SectionList.as_view(), name='scorecard_sections'),
    url(r'^sections/(?P<section>\d)/$',
        SectionDetail.as_view(), name='scorecard_section'),
    url(r'^sections/4/1.*',
        SectionDetail.as_view(), {'pk': 4}),
    url(r'^sections/(?P<section>\d)/(?P<subsection>\d)/$',
        SubsectionDetail.as_view(), name='scorecard_subsection'),
    url(r'^indicators/(?P<number>\d{1,2})/$',
        IndicatorDetail.as_view(), name='scorecard_indicator'),
]


# static view

urlpatterns += [
    url(r'^contributors/$', MPTTemplateView.as_view(
        template_name='scorecard/contributors.html'), name='scorecard_contributors'),
    url(r'^faq/$', MPTTemplateView.as_view(
        template_name='scorecard/faq.html'), name='scorecard_faq'),
    url(r'^methodology/$', MPTTemplateView.as_view(
        template_name='scorecard/methodology.html'), name='scorecard_methodology'),
    url(r'^$', IndexView.as_view(), name='scorecard'),
]

mptindicators/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('mptindicators.scorecard.urls')),
)

mptindicators/scorecard/models.py
from __future__ import unicode_literals
import random
from collections import defaultdict
from django.db import models
import re

class Region(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)

    def __unicode__(self):
        return self.name


class Country(models.Model):
    slug = models.SlugField()
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=2, blank=True)
    region = models.ForeignKey(Region, related_name='countries', blank=True, null=True)
    findings = models.TextField(blank=True)
    electoral_summary = models.TextField(blank=True)

    aggregate_score = models.PositiveSmallIntegerField(blank=True, null=True)
    in_law_score = models.PositiveSmallIntegerField(blank=True, null=True)
    in_practice_score = models.PositiveSmallIntegerField(blank=True, null=True)
 
    # apparently the names of countries drifted from Global Integrity's names,
    # so simply replacing whitespace with hyphens won't always work. this is a
    # map for fixing this ad-hoc.
    GI_NAME_VARIANTS = {
        'united-states-of-america': 'united-states',
        'trinidad-&-tobago': 'trinidad-and-tobago'
    }

    class Meta:
        ordering = ('name',)
        verbose_name_plural = "Countries"

    def __unicode__(self):
        return self.name

    def aggregate_score_chart_width(self):
        return self.aggregate_score if self.aggregate_score > 0 else 1

    @property
    def gi_name(self):
        gi_slug = self.name.lower().replace(' ', '-')
        return self.GI_NAME_VARIANTS.get(gi_slug, gi_slug)


class Section(models.Model):
    number = models.PositiveSmallIntegerField(default=0)
    name = models.CharField(max_length=255, blank=True)
    findings = models.TextField(blank=True)

    class Meta:
        ordering = ('number',)

    def __unicode__(self):
        return self.name


class Subsection(models.Model):
    section = models.ForeignKey(Section, related_name="subsections")
    number = models.PositiveSmallIntegerField(default=0)
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('section__number', 'number')

    def __unicode__(self):
        return '{} / {}'.format(self.section.name, self.name)


class Indicator(models.Model):

    UNKNOWN_TYPE = 0
    IN_LAW_TYPE = 1
    IN_PRACTICE_TYPE = 2
    OPEN_TYPE = 3

    TYPES = (
        (UNKNOWN_TYPE, 'unknown'),
        (IN_LAW_TYPE, 'in law'),
        (IN_PRACTICE_TYPE, 'in practice'),
        (OPEN_TYPE, 'open question'),
    )

    subsection = models.ForeignKey(Subsection, related_name='indicators')
    number = models.PositiveSmallIntegerField(default=0)
    name = models.TextField()
    criteria = models.TextField(blank=True)
    comment = models.TextField(blank=True)
    references = models.TextField(blank=True)
    type = models.PositiveSmallIntegerField(choices=TYPES, default=UNKNOWN_TYPE)

    class Meta:
        ordering = ('number',)

    def __unicode__(self):
        return self.name

    def headerfy_name(self):
        header_hash = defaultdict(lambda: '')
        max_header_length = 63
        for idx, n in enumerate(self.name):
            length_of_current_word = len(re.search("(\S*)", self.name[idx:-1]).groups()[0])
            if idx + length_of_current_word < max_header_length:
                header_hash['header'] += self.name[idx]
            else:
                header_hash['subheader'] += self.name[idx]
        return header_hash

    def header(self):
        return self.headerfy_name()['header']

    def subheader(self):
        return self.headerfy_name()['subheader']


class IndicatorScore(models.Model):
    indicator = models.ForeignKey(Indicator, related_name="indicator_scores")
    country = models.ForeignKey(Country, related_name="indicator_scores")
    score = models.PositiveSmallIntegerField(blank=True, null=True)
    comment = models.TextField(blank=True)
    sources = models.TextField(blank=True)

    class Meta:
        ordering = ('country__name', 'indicator__number')

    def score_chart_width(self):
        return self.score if self.score > 0 else 1

    def score_for_display(self):
        if self.score is None:
            return '--'
        if self.indicator.type == Indicator.IN_LAW_TYPE:
            return self.in_law_score()
        else:
            return self.score

    def in_law_score(self):
        return {
            0: 'NO',
            50: 'MODERATE',
            100: 'YES'
        }[self.score]

    @property
    def rendered_sources(self):
        lines = [l.strip() for l in self.sources.split('\n')]
        return '\n'.join('* {}'.format(l) for l in lines if l)

    @property
    def is_in_law(self):
        return self.indicator.type == Indicator.IN_LAW_TYPE


class Aggregate(models.Model):
    country = models.ForeignKey(Country, related_name="aggregates")
    section = models.ForeignKey(
        Section, related_name="aggregates", blank=True, null=True)
    subsection = models.ForeignKey(
        Subsection, related_name="aggregates", blank=True, null=True)
    score = models.PositiveSmallIntegerField(blank=True, null=True)

    def score_chart_width(self):
        return self.score if self.score > 0 else 1

mptindicators/scorecard/views.py
import unicodecsv as csv
from contextlib import closing
from cStringIO import StringIO
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import View, DetailView, ListView, TemplateView
from django.utils.text import slugify
from .models import Country, Section, Subsection, Indicator, Aggregate


class MPTView(View):
    def get_context_data(self, **kwargs):
        context = super(MPTView, self).get_context_data(**kwargs)
        context['countries'] = Country.objects.all()
        context['sections'] = Section.objects.all()

        return context


class MPTOrderedView(MPTView):
    def get_context_data(self, **kwargs):
        context = super(MPTOrderedView, self).get_context_data(**kwargs)
        context['ordering'] = self.request.GET.get('o')
        return context


class MPTSectionView(MPTOrderedView):
    def get_context_data(self, **kwargs):
        context = super(MPTSectionView, self).get_context_data(**kwargs)
        if 'section' not in context:
            context['section'] = self.object.section
        context['aggregates'] = Aggregate.objects.filter(
            section=context['section'],
            subsection=context.get('subsection', None))
        if context['ordering'] == 'name_asc':
            context['aggregates'] = context['aggregates'].order_by(
                'country__name')
        elif context['ordering'] == 'name_desc':
            context['aggregates'] = context['aggregates'].order_by(
                '-country__name')
        elif context['ordering'] == 'score_asc':
            context['aggregates'] = context['aggregates'].order_by(
                'score',
                'country__name')
        elif context['ordering'] == 'score_desc':
            context['aggregates'] = context['aggregates'].order_by(
                '-score',
                'country__name')
        return context


class IndexView(MPTView, TemplateView):

    template_name = 'scorecard/index.html'

    def get_context_data(self, **kwargs):

        context = super(IndexView, self).get_context_data(**kwargs)
        qs = context['countries']

        ordering = self.request.GET.get('o')

        if ordering == 'name_asc':
            qs = qs.order_by('name')
        if ordering == 'name_desc':
            qs = qs.order_by('-name')
        if ordering == 'score_asc':
            qs = qs.order_by('aggregate_score', 'name')
        if ordering == 'score_desc':
            qs = qs.order_by('-aggregate_score', 'name')

        context['ordering'] = ordering
        context['indicator_countries'] = qs

        return context


class CountryList(MPTView, ListView):
    model = Country


class CountryDetail(MPTView, DetailView):
    model = Country
    slug_field = 'code'
    slug_url_kwarg = 'code'


class IndicatorList(MPTView, ListView):
    model = Indicator


class SectionList(MPTView, ListView):
    model = Section

    def get_queryset(self):
        return Section.objects.prefetch_related("subsections__indicators")


class SectionDetail(MPTSectionView, DetailView):
    model = Section
    slug_field = "number"
    slug_url_kwarg = "section"

    def get_queryset(self):
        return Section.objects.prefetch_related("subsections__indicators")


class SubsectionDetail(MPTSectionView, DetailView):
    model = Subsection
    slug_field = "number"
    slug_url_kwarg = "subsection"

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        snum = self.kwargs.get('section', None)
        ssnum = self.kwargs.get('subsection', None)
        return queryset.get(section__number=snum, number=ssnum)

    def get_queryset(self):
        return Subsection.objects.prefetch_related("indicators").select_related("section")

    def get_context_data(self, **kwargs):
        context = super(SubsectionDetail, self).get_context_data(**kwargs)
        context['section'] = self.object.section
        return context


class IndicatorDetail(MPTOrderedView, DetailView):
    model = Indicator
    slug_field = "number"
    slug_url_kwarg = "number"

    def get_queryset(self):
        qs = Indicator.objects.prefetch_related(
            "indicator_scores").select_related("subsection__section")
        return qs

    def get_context_data(self, **kwargs):

        context = super(IndicatorDetail, self).get_context_data(**kwargs)
        context['subsection'] = self.object.subsection
        context['section'] = self.object.subsection.section

        indicator_scores = self.object.indicator_scores.all()

        if context['ordering'] == 'name_asc':
            indicator_scores = indicator_scores.order_by('country__name')
        if context['ordering'] == 'name_desc':
            indicator_scores = indicator_scores.order_by('-country__name')
        if context['ordering'] == 'score_asc':
            indicator_scores = indicator_scores.order_by('score', 'country__name')
        if context['ordering'] == 'score_desc':
            indicator_scores = indicator_scores.order_by('-score', 'country__name')

        context['indicator_scores'] = indicator_scores

        return context


#
# data download views
#

class CountryData(DetailView):

    def get(self, request, *args, **kwargs):
        country = get_object_or_404(Country, code=kwargs['code'])

        with closing(StringIO()) as bffr:

            writer = csv.writer(bffr)

            writer.writerow(
                ('indicator', 'question', 'type', 'score',
                 'section', 'section_name', 'subsection', 'subsection_name'))

            for score in country.indicator_scores.select_related():

                indicator = score.indicator
                subsection = indicator.subsection
                section = subsection.section

                row = (
                    indicator.number,
                    indicator.name,
                    indicator.get_type_display(),
                    score.score,
                    section.number,
                    section.name,
                    subsection.number,
                    subsection.name,
                )

                writer.writerow(row)

            content = bffr.getvalue()

        filename = 'indicators_{}.csv'.format(slugify(country.name))

        resp = HttpResponse(content, content_type='text/csv')
        resp['Content-Disposition'] = 'attachment; filename={}'.format(filename)

        return resp

mptindicators/scorecard/templates/scorecard/contributors.html
{% extends "scorecard/base.html" %}

{% block sidebar %}
{% endblock %}
{% block pagetitle %}<span class="indicator-num"></span>  <h2 class="alpha">Project Contributors</h2>{% endblock %}

{% block content %}

<div class="mpt-content-area row full-width index">
    <div class="small-12 columns">
        <div class="page-content">
            <div class="row">
                <div class="columns small-12 contributors">

					<h3>Researchers</h3>
					<div class="row">
						<ul class="medium-6 large-3 columns no-bullet">
							<li>Inesa Hila</li>
							<li>Maria Rosario Pavese</li>
							<li>Alan Wolfe</li>
							<li>Mathias Huter</li>
							<li>Shazada Akram</li>
							<li>Jef Smulders</li>
							<li>Diego Ayo</li>
							<li>Ivana Koralijic</li> 
							<li>Ntibinyane Ntibinyane</li>
							<li>Natalia Paiva</li>
							<li>Ekaterina Rashkova</li>
							<li>Jeannette von Wolfersdorff</li>
							<li>Sandra Ximenes Martinez Rosas</li>
							<li>Eduardo Nunez</li>
						</ul>
						<ul class="medium-6 large-3 columns no-bullet">
							<li>Martina Topic</li>
							<li>Veronica Alvarez</li>
							<li>Irine Urushadze</li>
							<li>Anne-Christine Wegener</li>
							<li>Franklin Oduro</li>
							<li>Sandor Lederer</li>
							<li>Madhumita Datta Mitra</li>
							<li>Danang Widoyoko</li>
							<li>Tomer Avital</li>
							<li>Daniela Picco</li>
							<li>Masayoshi Kuboya</li>
							<li>Kennedy Masime</li>
							<li>John Power</li>
							<li>Elsy Melkonian</li>
						</ul>
						<ul class="medium-6 large-3 columns no-bullet">
							<li>Augustine Magolowondo</li>
							<li>Joseph Tong</li>
							<li>Rocio Moreno Lopez</li>
							<li>Ini Ekott</li>
							<li>Zahid Abdulla</li>
							<li>Lina Antara</li>
							<li>Jazmin Acuna</li>
							<li>Caroline Gibu</li>
							<li>Che de los Reyes</li>
							<li>Adam Sawicki</li>
							<li>Sergiu Ghergina</li>
							<li>Boris Demidov</li>
							<li>Ignatius Ssuna</li>
							<li>Maja Sandic</li>
						</ul>
						<ul class="medium-6 large-3 columns no-bullet">
							<li>Alenka Krasovec</li>
							<li>Alan Agassi</li>
							<li>Gary Pienaar</li>
							<li>Dissanayake Dasnayaka Mudiyanselage</li>
							<li>Ann-Kristin Kölln</li>
							<li>Hanna Hindstrom</li>
							<li>Josh Drayton</li>
							<li>Omer Faruk Genckaya</li>
							<li>Linnea Mills</li>
							<li>Marina Mas</li>
							<li>Angel Alvarez</li>
						</ul>
					</div>
					<h3>Peer Reviewers</h3>
					<div class="row">
						<ul class="medium-6 large-3 columns no-bullet">
							<li>Aranita Brahaj</li>
							<li>Delia Ferreira Rubio</li>
							<li>Norm Kelly</li>
							<li>Hubert Sickinger</li>
							<li>Tanvir Mahmud</li>
							<li>Jean Faneil</li>
							<li>Miguel Centellas</li>
							<li>Drazen Simic</li>
							<li>Sonny Serite</li>
							<li>Sergio Praca</li>
							<li>Rumen Stefanov</li>
							<li>Emilio Moya</li>
							<li>Andres Schipani</li>
							<li>Diego Padilla</li>
						</ul>
						<ul class="medium-6 large-3 columns no-bullet">
							<li>Zorislav Antun Petrovic</li>
							<li>Carolina Curvale</li>
							<li>Tinatin Ninua</li>
							<li>Daniel Dietrich</li>
							<li>Sef Ashiagbor</li>
							<li>Balasz Romhanyi</li>
							<li>Nivell Rayda</li>
							<li>Assaf Shapira</li>
							<li>Eugenio Pizzimenti</li>
							<li>Moses Owuor</li>
							<li>Samuel Kimeu</li>
							<li>Kyung Park</li>
							<li>Ghassan Elbitar</li>
							<li>Collins Mtika</li>
						</ul>
						<ul class="medium-6 large-3 columns no-bullet">
							<li>Terence Gomez</li>
							<li>Fransje Molenaar</li>
							<li>Victor Adetula</li>
							<li>Zahid Ahmed</li>
							<li>Richard Morales</li>
							<li>Osmar Gomez</li>
							<li>Samuel Rotta</li>
							<li>Joy Aceron</li>
							<li>Fernando Casal Bertoa</li>
							<li>Sorina Soare</li>
							<li>Alisa Voznaya</li>
							<li>Victor Nkindi</li>
							<li>Lazar Maricevic</li>
						</ul>
						<ul class="medium-6 large-3 columns no-bullet">
							<li>Transparency International Slovenia</li>
							<li>Marcus Pelto</li>
							<li>Collette Herzenberg</li>
							<li>Paikiasothy Saravanamuttu</li>
							<li>Magnus Ohman</li>
							<li>Ann-Marie Bissessar</li>
							<li>Seda Kirdar</li>
							<li>Thomas Warren</li>
							<li>Robert Boatright</li>
							<li>Richard Briffault</li>
							<li>Mariana Rethen</li>
							<li>Luis Gomez Calcano</li>
						</ul>
					</div>
					<h3>Money, Politics, and Transparency Reference Group</h3>
					<ul class="small-12 columns no-bullet">
						<li>Sarah Birch</li>
						<li>Finn Heinrich</li>
						<li>Sam Jones</li>
						<li>Richard Katz</li>
						<li>Sheila Krumholtz</li>
						<li>Vincent Lazatin</li>
						<li>Fernando Straface</li>
						<li>Bill Sweeney</li>
						<li>Andreas Ufen</li>
						<li>Henni van Vuuren</li>
					</ul>

					<h3>Global Integrity Research Team</h3>
					<ul class="small-12 columns no-bullet">
						<li>Hazel Feigenblatt, Managing Director, Research</li>
						<li>Johanness Tonn, Manager, Research</li>
						<li>Michael Moses, Manager, Research</li>
						<li>Scott Rumpsa, Manager, Research</li>
					</ul>

				</div>
			</div>
		</div>
	</div>
</div>


{% endblock %}

mptindicators/scorecard/templates/scorecard/country_detail.html
{% extends "scorecard/base.html" %}
{% load md2 %}
{% load scorecard_tags %}
{% load staticfiles %}

{% block og %}
	<meta property="og:url" content="http://data.moneypoliticstransparency.org{% url 'scorecard_country' country.code %}">
	<meta property="og:title" content="{{ country.name }} Scorecard">
	<meta property="og:description" content="Money, Politics and Transparency aims to generate research, analysis and global norms that civic organizations, elected officials, regulators and the media can use to build more transparent political financing systems in any country.">
{% endblock %}

{% block pagetitle %}<h2 class="alpha">{{ object.name }}</h2>{% endblock %}

{% block content %}

<div class="mpt-content-area row full-width index">
	<div class="small-12 columns">
		<div class="page-content">
			<div class="row">
				<div class="columns small-8">
					<div class="country-score {% score_class country.aggregate_score %}">
						<dl class="score composite">
						<dt>composite</dt>
						<dd>{{ country.aggregate_score }}</dd>
						</dl>
						<div class="country-meta clearfix">
							<span class="chart">
				                <span class="count">{{ country.aggregate_score }}</span>
				                <span class="index" style="width: {{ country.aggregate_score_chart_width }}%"></span>
				                <span class="ticks"></span>
				            </span>

				            <h4>{{ country.name }}</h4>
				            <dl class="breakdown">
				            	<dt>In law</dt>
				            	<dd><span class="score {% score_class country.in_law_score %}">{{ country.in_law_score }}</span></dd>
				            	<dt>In practice</dt>
				            	<dd><span class="score {% score_class country.in_practice_score %}">{{ country.in_practice_score }}</span></dd>
				            </dl>
			            </div>
					</div>
					<div class="country-summary">
						{{ country.findings|markdown }}
					</div>

				</div>
				<div class="columns small-4">
					<aside class="aside-content-block meta-nav-indicators">
						<h3>Learn more</h3>
						<ul class="no-bullet">
							<li><a class="icon download" href="http://assets.sunlightfoundation.com.s3.amazonaws.com/mpt/bulk.zip">Download full dataset</a></li>
							<li><a class="icon country-details" target="_blank" href="https://www.globalintegrity.org/research/{{ country.gi_name }}/">Country details</a></li>

						</ul>
					</aside>
				</div>
			</div>
			<div class="row">
				<div class="columns small-12">

					<ul class="tabs" data-tab>
						  <li class="tab-title active"><a href="#indicators">Indicators</a></li>
						  <li class="tab-title"><a href="#summary">Electoral System Summary</a></li>
						</ul>
						<div class="tabs-content">
							<div class="country-indicators content active" id="indicators">
								<ul class="accordion" data-accordion>
									{% regroup object.indicator_scores.all by indicator.subsection.section as section_list %}
									{% for section in section_list %}
									  {% section_agg country section.grouper as section_score %}
									  <li class="accordion-navigation">
										<a class="expand" href="#panel-{{ section.grouper.number }}">expand button!</a>
										<div class="section {% score_class section_score.score %}">
											<h4>{{ section.grouper.name }}</h4>
											<a href="{% url 'scorecard_section' section.grouper.number %}">More about category</a>
											<dl class="composite score">
												<dt>composite</dt>
												<dd>{{ section_score.score }}</dd>
											</dl>
											<!--
											<dl class="breakdown">
								            	<dt>In law</dt>
								            	<dd><span class="score two">23</span></dd>
								            	<dt>In practice</dt>
								            	<dd><span class="score four">56</span></dd>
								            </dl>
								            -->
							            </div>
									    <div id="panel-{{ section.grouper.number }}" class="content">
										    <ul class="accordion" data-accordion>
										      	{% regroup section.list by indicator.subsection as subsection_list %}
										      	{% for subsection in subsection_list %}
										      		<li class="accordion-navigation">

														<a class="expand" href="#panel-{{ section.grouper.number }}-{{ subsection.grouper.number }}">expand button!</a>
														<div class="section">
											    			<h5>{{ subsection.grouper.name }}</h5>
											    			<a href="{% url 'scorecard_subsection' section.grouper.number subsection.grouper.number %}">More about category</a>
											    		</div>
											    		<div id="panel-{{ section.grouper.number }}-{{ subsection.grouper.number }}" class="indicator content ">
												    		<ul class="accordion" data-accordion>
													      		{% for indicator_score in subsection.list %}
													      			<li class="accordion-navigation" id="indicator_{{indicator_score.indicator.number}}">
													      				<a class="expand" href="#panel-ind{{ indicator_score.indicator.number }}">expand button!</a>
														                <div class="section clearfix">
															                <span class="indicator-num">{{ indicator_score.indicator.number }}</span>
															                <dl class="indicator-score">
														                    	<dt class="text-replace">
														                    		Score
														                    	</dt>
														                    	<dd>
														                    		{{ indicator_score.score_for_display }}
														                    	</dd>
														                    </dl>
													                   	 	<h6>{{ indicator_score.indicator.name }}<a href="{% url 'scorecard_indicator' indicator_score.indicator.number %}">More about indicator</a></h6>
														                </div>
													                    <div id="panel-ind{{ indicator_score.indicator.number }}" class="content ">
														                    <div class="comment">
															                    {{ indicator_score.comment|markdown }}
														                    </div>
														                    <div class="row sub-content">
													                    	<div class="criteria large-6 columns">
													                    		<h6>Scoring Criteria</h6>
													                    		<p>{{ indicator_score.indicator.criteria|markdown }}</p>
													                    	</div>
														                    <div class="sources large-6 columns">
														                    	<h6>Sources</h6>
														                    	{{ indicator_score.sources|markdown }}
														                    </div>
														                    </div>
														                </div>
													                </li>
										        				{% endfor %}

															</ul>
									    				</div>
													</li>
												{% endfor %}
											</ul>
										</div>
									{% endfor %}
								</div>
								<div class="electoral-summary content" id="summary">
									{{ country.electoral_summary|markdown }}
								</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block js %}
	<script type="text/javascript" src="{% static 'js/sources.js' %}"></script>
{% endblock %}

mptindicators/scorecard/templates/scorecard/country_list.html
{% extends "scorecard/base.html" %}

{% block content %}
    <h1>Countries</h1>
    <ul>
        {% for country in object_list %}
            <li><a href="{% url 'scorecard_country' country.slug %}">{{ country }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

mptindicators/scorecard/templates/scorecard/faq.html
{% extends "scorecard/base.html" %}
{% load pages_tags %}

{% block sidebar %}
{% endblock %}
{% block pagetitle %}<span class="indicator-num"></span>  <h2 class="alpha">Project Contributors</h2>{% endblock %}

{% block content %}

<div class="mpt-content-area row full-width index">
    <div class="small-12 columns">
        <div class="page-content">
            <div class="row">
                <div class="columns small-12">
                	{% chunk 'faq' %}
				</div>
			</div>
		</div>
	</div>
</div>


{% endblock %}

mptindicators/scorecard/templates/scorecard/methodology.html
{% extends "scorecard/base.html" %}
{% load pages_tags %}

{% block sidebar %}
{% endblock %}

{% block pagetitle %}<span class="indicator-num"></span>  <h2 class="alpha">Methodology</h2>{% endblock %}

{% block content %}

<div class="mpt-content-area row full-width index">
    <div class="small-12 columns">
        <div class="page-content">
            <div class="row">
                <div class="columns small-12">
                	{% chunk 'methodology' %}
				</div>
			</div>
		</div>
	</div>
</div>


{% endblock %}

mptindicators/scorecard/templates/scorecard/section_list.html
{% extends "scorecard/base.html" %}

{% block content %}
    <h1>Sections</h1>
    <ul>
        {% for section in object_list %}
            <li>
                <a href="{% url 'scorecard_section' section.number %}">{{ section.name }}</a>
                <ul>
                    {% for subsection in section.subsections.all %}
                        <li>
                            <a href="{% url 'scorecard_subsection' section.number subsection.number %}">{{ subsection }}</a>
                            <ul>
                                {% for indicator in subsection.indicators.all %}
                                    <li>
                                        <a href="{% url 'scorecard_indicator' indicator.number %}">{{ indicator.number }}. {{ indicator.name }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </li>
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
    </ul>
{% endblock %}